import Head from 'next/head';

export const metadata = {
  title: 'Next.js  Returns',
  description: 'Generated by Den',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <meta name="referrer" content="origin" />
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  )
}
